### ISSUE TITLE
Approximate equivalents to this code?

### ISSUE THREAD

**Issue by ethindp** [icedland/iced#137]
I'd like to make a program that generates CPU instructions instead of needing to assemble them and link them in the program at compilation time. However, the assembly I'm basing it off of uses directives like `.word`, `.byte`, etc. As an example, I don't know how I'd represent this in Rust with iced-x86:
```asm
.rodata
/* Global descriptor table */
gdt:
/* Use null entry to store pointer to GDT. */
.global gdt_ptr
gdt_ptr:
	.word gdt_end - gdt - 1;
	.int gdt
	.align 8
gdt_code:
	.quad 0x00209A0000000000

gdt_data:
	.quad 0x0000920000000000

gdt_end:
```
Additionally, the code uses other directives like this:
```asm
.set CODE_SELECTOR, gdt_code - gdt
.set DATA_SELECTOR, gdt_data - gdt
```
And then employs these like so:
```asm
	mov $null_ivt_ptr_offset, %bx
	sub %ax, %bx

	lidtl %cs:(%bx)

	mov $gdt_ptr_offset, %bx
	sub %ax, %bx

	lgdtl %cs:(%bx)
// ...
	ljmpl $CODE_SELECTOR, $long_mode_start
// ...
.code64
long_mode_start:
// ...
```
So my questions are:

1. How are directives like `.set`, `.byte`, `.quad`, ..., represented if I were to generate these instructions? Would I need to actually write an object file for this to work?
2. How do I produce labels and then produce instructions to jump to them?

I hope none of this seems too ambiguous.

**Comment by 0xd4d** [comment]
`.set` looks like `equ` in masm, so just an expression/constant.

`.byte`/etc = `Instruction::with_declare_byte()`/etc

Labels: see the example in README.
