### ISSUE TITLE
Why is DnSpy archived? (DO NOT DELETE)

### ISSUE THREAD

**Issue by Hedreon** [icedland/iced#148]
_Everyone needs answers for this._

Though, I know you've made a new account but why was it shut down? Is it because you moved accounts? or... is it because you gave up on it?

Do not delete this, close this issue after this has been answered. everyone, needs, answers for this kind of topic.

**Comment by Hedreon** [comment]
Did you lose reputation or something?

**Comment by Hedreon** [comment]
I need this answered.

**Comment by Symbai** [comment]
> Everyone needs answers for this.

I don't, because I respect his decision and I'm not abusing this repo and the issue function only to satisfy my curiosity. Free lesson for you: If he wants to share the why, he would have done it just like he did with his new account.
