### ISSUE TITLE
AssemblerRegisterNN should have a public constructor

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [icedland/iced#158]
AssemblerRegister32 (and similar) should have its internal constructor taking a Register be public.

I'm currently changing some code in a project to use the high-level assembler instead of manually creating instructions and adding them to an InstructionList. One of my methods accepts an InstructionList (now Assembler), a Register and a boolean indicating x86/x64. When inserting a call instruction into the Assembler, it only accepts AssemblerRegister32, AssemblerRegister64, etc. It doesn't seem possible to create these directly from a Register.

For now, I'm constructing the Instruction myself and adding it using AddInstruction, but not being able to convert a Register to an AssemblyRegisterNN seems like a shortcoming.

**Comment by wtfsck** [comment]
Should be easy to fix if you want to send a PR

https://github.com/icedland/iced/blob/master/src/csharp/Intel/Iced/Intel/Assembler/AssemblerRegister.tt
