### ISSUE TITLE
How do we handle the EXE header?

### ISSUE THREAD

**Issue by jt0dd** [icedland/iced#167]
https://stackoverflow.com/questions/67547279/how-is-the-header-of-an-exe-disassembled-differently-in-contrast-to-the-rest-of

Basically I'm trying to disassemble an EXE and the header needs to be handled differently than the examples you gave. I'm newly learning Assembly so my understanding is pretty rudimentary.

**Comment by wtfsck** [comment]
This lib only understands x86 instructions so you have to use some other lib to find the code in an executable. Seems like you're using Rust, so you could use goblin: https://crates.io/crates/goblin

Their PE example: https://github.com/m4b/goblin/blob/master/examples/dotnet_pe_analysis.rs
