### ISSUE TITLE
RustSec advisory for versions <= v1.10.3

### ISSUE THREAD

**Issue by landaire** [icedland/iced#168]
I was running Miri on my project and saw a curious violation:

```
error: Undefined Behavior: memory access failed: pointer must be in-bounds at offset 4, but is outside bounds of alloc90797 which has size 3
    --> C:\Users\lander\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\slice\mod.rs:365:18
     |
365  |         unsafe { &*index.get_unchecked(self) }
     |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ memory access failed: pointer must be in-bounds at offset 4, but is outside bounds of alloc90797 which has size 3
     |
     = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
     = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
             
     = note: inside `core::slice::<impl [u8]>::get_unchecked::<usize>` at C:\Users\lander\.rustup\toolchains\nightly-x86_64-pc-windows-msvc\lib\rustlib\src\rust\library\core\src\slice\mod.rs:365:18
     = note: inside `iced_x86::Decoder::new` at C:\Users\lander\.cargo\registry\src\github.com-1ecc6299db9ec823\iced-x86-1.9.1\src\decoder\mod.rs:457:42
note: inside `Emulator::run` at src\lib.rs:563:27
    --> src\lib.rs:563:27
     |
563  |         let mut decoder = Decoder::new(self.bitness, bytes, self.decoder_options);
```

Per the Rust docs for [`get_unchecked`](https://doc.rust-lang.org/std/primitive.slice.html#method.get_unchecked):

>Calling this method with an out-of-bounds index is undefined behavior even if the resulting reference is not used.

Full code context: https://github.com/icedland/iced/blob/8209aa94f9b62c5be606292038fb86eee232fb85/src/rust/iced-x86/src/decoder.rs#L732

It looks like this code was changed in https://github.com/icedland/iced/commit/3c607a003e03b773108401d109167d1840487dce and no longer contains a call to `get_unchecked`.

I'm mostly submitting this issue as an FYI, but IMO a [RustSec advisory](https://rustsec.org/) should be published for versions prior to this fix to prevent undefined behavior in Rust applications consuming this library. If you agree I'd be happy to submit the advisory.

**Comment by wtfsck** [comment]
Seems like that code was removed prior to 1.11.0 (i.e., <= 1.10.3), not 1.11.3.

> If you agree I'd be happy to submit the advisory.

Sure you can do it.

**Comment by wtfsck** [comment]
Fixed the title

**Comment by wtfsck** [comment]
Closing this since you've sent the PR.
