### ISSUE TITLE
Assembler creates unnecessary instructions

### ISSUE THREAD

**Issue by Symbai** [icedland/iced#173]
## Code
```C#
var c = new Assembler(64);
var label1 = c.CreateLabel();
c.call(0x7FFD7E530940);
c.jmp(label1);
c.Label(ref label1);
c.mov(rax, 1);
var stream = new MemoryStream();
c.Assemble(new StreamCodeWriter(stream), 0x00403C70);
Console.WriteLine(BitConverter.ToString(stream.ToArray()).Replace("-", string.Empty));
```

## Result
```
FF 15 12000000        - call qword ptr [024D0018]
EB 00                 - jmp 024D0008
48 B8 0100000000000000 - mov rax,0000000000000001
CC                    - int 3 
CC                    - int 3 
CC                    - int 3 
CC                    - int 3 
CC                    - int 3 
CC                    - int 3 
40 09 53 7E           - or [rbx+7E],edx
FD                    - std 
7F 00                 - jg 024D001F
```
## Expected:
```
FF 15 0C000000        - call qword ptr [024D0012]
EB 00                 - jmp 024D0008
48 B8 0100000000000000 - mov rax,0000000000000001
40 09 53 7E           - or [rbx+7E],edx
FD                    - std 
7F 00                 - jg 024D0019
```

Why does it creates so many unnecessary int3 instructions, is this a bug or intended (and if so, why?)?

**Comment by wtfsck** [comment]
You have a `CALL NEAR` instruction that's too far away so it creates a `CALL MEM` and create a location with the offset of the target. The mem location is 8-byte aligned. This can be disabled but unless you do the same thing as iced did, you'll get an error when encoding it.

**Comment by Symbai** [comment]
I know but why is it (8 byte) aligned? The code still executes when its unaligned

**Comment by wtfsck** [comment]
Yes and it results in less bytes but there can be penalties when accessing the memory. I suggest you google `data alignment` or something similar for longer explanations.

**Comment by Symbai** [comment]
Where is the check in code so I can turn this off myself?

**Comment by ethindp** [comment]
You definitely don't want to turn that off. Its not just for data alignment; INT3 and that other stuff is even generated by compilers -- its a trap. Its a code path that, in theory, should *never* be executed. But if someone manipulates the execution flow to try to execute that code path, the trap will kick in and the program will halt.
As I said above though, under normal circumstances it should never be executed; you have an unconditional jump instruction, jumping you to 024D0008h, and unless I'm mistaken, the trap is immediately following that jump. That code will never be reached under normal circumstances, which is exactly the point. But if it is reached, then you definitely know that someone is tampering with your program.

**Comment by Symbai** [comment]
> But if it is reached, then you definitely know that someone is tampering with your program.

No, I don't. And yes, I definitely want to turn that off. I have my reasons to do so which are far away from what you think I'm doing with the assembler. I only need to know how I can do this. I appreciate your feedback but please just comment if you know how to turn this off, thank you.

**Comment by ethindp** [comment]
I don't think you can, and I'm confused why you'd want to. Again, that
trap is there for a good reason. You could, in theory, remove the
instructions by hand, but that would get messy pretty quickly.

On 6/15/21, Symbai ***@***.***> wrote:
>> But if it is reached, then you definitely know that someone is tampering
>> with your program.
>
> No, I don't. And yes, I definitely want to turn that off. I have my reasons
> to do so which are far away from what you think I'm doing with the
> assembler. I only need to know how I can do this. I appreciate your feedback
> but please just comment if you know how to turn this off, thank you.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/icedland/iced/issues/173#issuecomment-861198315


-- 
Signed,
Ethin D. Probst
