### ISSUE TITLE
[Question] Is there a function to parse string to Code enum?

### ISSUE THREAD

**Issue by BlackOfWorld** [icedland/iced#176]
I think title says all. I'm writing a software that allows the user to assemble by instruction and disassemble by opcodes.

If there is, please let me know. Thanks!

**Comment by wtfsck** [comment]
If you mean an assembler that takes a string and spits out bytes, no, there's none yet.

**Comment by BlackOfWorld** [comment]
Yes that's what I meant. Sad to see it's not implemented yet. Will try to implement it and if I'll succeed I'll create a PR.
