### ISSUE TITLE
Access operand constraints from Instruction object

### ISSUE THREAD

**Issue by paulfariello** [icedland/iced#183]
It would be great to have access to the operand constraint as defined in ops_tables from encoder directly from an existing `Instruction` object.

https://github.com/icedland/iced/blob/000947c762d885fe0302ce5e03ce7e2c05e85c63/src/rust/iced-x86/src/encoder/ops_tables.rs#L23-L26

It can be useful to know this constraint when one want to replace an operand.

**Comment by paulfariello** [comment]
I can spend time implementing this if you have any guidelines on how `ops_tables` could be presented (or recreated from cs files) within `Instruction`.

**Comment by wtfsck** [comment]
You can get the `OpCodeInfo` which should have all of that info, see `OpCodeOperandKind` enum. `instruction.op_code()` should give you that class and then call its `op_kinds()` method to get all the values (`OpCodeOperandKind` enum values).

**Comment by paulfariello** [comment]
That's exactly what I was looking for. Thanks.
