### ISSUE TITLE
RFC: Support for an `is_string_op` for LODS/STOS/MOVS/CMPS/SCAS

### ISSUE THREAD

**Issue by woodruffw** [icedland/iced#184]
This family of instructions has interesting microarchitectural behavior (complex rollback handling, fast-string mode, etc.), and it'd be nice to be able to check whether a particular `Instruction` or `Code` is a string operation without having to compare against every member of the mnemonic/code family.

I'm happy to implement this; just wanted to check whether it's wanted first and whether you'd prefer it on `Instruction`, `Code`, or `Mnemonic` 🙂

**Comment by wtfsck** [comment]
Yes, that sounds like a useful method!

Is there a reason you didn't include `INS`/`OUTS` instructions? They're also string instructions.

> I'm happy to implement this; just wanted to check whether it's wanted first and whether you'd prefer it on `Instruction`, `Code`, or `Mnemonic` slightly_smiling_face

`Code` should get the impl and then `Instruction` has a method that just calls that new `Code` method.

This requires the `instr_info` feature so could be added to the same `impl` block as `condition_code()` in `code.rs`.

**Comment by woodruffw** [comment]
> Is there a reason you didn't include `INS`/`OUTS` instructions? They're also string instructions.

Nope, that was an oversight! I'll include those as well.

> Code should get the impl and then Instruction has a method that just calls that new Code method.
> This requires the instr_info feature so could be added to the same impl block as condition_code() in code.rs.

Sounds good. I'll look into writing those.

**Comment by woodruffw** [comment]
> This requires the instr_info feature so could be added to the same impl block as condition_code() in code.rs.

Oh, I went a little bit overboard on this and ended up modifying the instruction table + adding a flag to do this in the codegen instead. But I can switch it over to a manual implementation instead 😅
