### ISSUE TITLE
Address bug?

### ISSUE THREAD

**Issue by vlacre** [icedland/iced#191]
Hello!
I have the following code:

ulong je = 0x7FF7C5F6002D

ulong jmp = 0x7FF7C5F60078

`            var asm = new Assembler(64);

            asm.push(rax);
            asm.mov(rax,__[rcx + 0x00000294]);
            asm.test(rax,rax);
            asm.je(je);
            asm.mov(__[0x7FF7C5F60043],rax);
            asm.mov(rax,__[rax + 0x00000478]);
            asm.test(rax, rax);
            asm.je(je);
            asm.mov(__[0x7FF7C5F6004B],rax);
            asm.pop(rax);
            asm.jmp(jmp);`

The je and jmp instructions work fine with addresses, but the mov instruction has a bug with the address? Here's the result:

`
7FF7C5F60000 - 50                    - push rax
7FF7C5F60001 - 48 8B 81 94020000     - mov rax,[rcx+00000294]
7FF7C5F60008 - 48 85 C0              - test rax,rax
7FF7C5F6000B - 74 20                 - je 7FF7C5F6002D
7FF7C5F6000D - 48 A3 4B00FBC5FFFFFFFF - mov [FFFFFFFFC5FB004B],rax
7FF7C5F60017 - 48 8B 80 78040000     - mov rax,[rax+00000478]
7FF7C5F6001E - 48 85 C0              - test rax,rax
7FF7C5F60021 - 74 0A                 - je 7FF7C5F6002D
7FF7C5F60023 - 48 A3 4300F6C5FFFFFFFF - mov [FFFFFFFFC5F60043],rax
7FF7C5F6002D - 58                    - pop rax
7FF7C5F6002E - E9 787EB900           - jmp 7FF7C5F60078

`

Why is the address converted incorrectly in the mov instruction? Where there took FFFF? How can this be fixed?

**Comment by wtfsck** [comment]
Yes, it's a bug here:

https://github.com/icedland/iced/blob/8aab1983a5228bb6c6a2d825dfe7f3d10147e1cf/src/csharp/Intel/Iced/Intel/Assembler/AssemblerMemoryOperand.cs#L186

The `(int)` cast should be removed.

Workaround:

Change these:

```C#
asm.mov(__[0x7FF7C5F60043], rax);
asm.mov(__[0x7FF7C5F6004B], rax);
```

to

```C#
asm.AddInstruction(Instruction.Create(Code.Mov_moffs64_RAX, new MemoryOperand(Register.None, Register.None, 1, 0x7FF7C5F60043, 8, false, Register.None), Register.RAX));
asm.AddInstruction(Instruction.Create(Code.Mov_moffs64_RAX, new MemoryOperand(Register.None, Register.None, 1, 0x7FF7C5F6004B, 8, false, Register.None), Register.RAX));
```

**Comment by vlacre** [comment]
> Yes, it's a bug here:
> 
> https://github.com/icedland/iced/blob/8aab1983a5228bb6c6a2d825dfe7f3d10147e1cf/src/csharp/Intel/Iced/Intel/Assembler/AssemblerMemoryOperand.cs#L186
> 
> The `(int)` cast should be removed.
> 
> Workaround:
> 
> Change these:
> 
> ```cs
> asm.mov(__[0x7FF7C5F60043], rax);
> asm.mov(__[0x7FF7C5F6004B], rax);
> ```
> 
> to
> 
> ```cs
> asm.AddInstruction(Instruction.Create(Code.Mov_moffs64_RAX, new MemoryOperand(Register.None, Register.None, 1, 0x7FF7C5F60043, 8, false, Register.None), Register.RAX));
> asm.AddInstruction(Instruction.Create(Code.Mov_moffs64_RAX, new MemoryOperand(Register.None, Register.None, 1, 0x7FF7C5F6004B, 8, false, Register.None), Register.RAX));
> ```

Oh, thank u very much! Now it works!
