### ISSUE TITLE
Incorrect base register for instructions such as call qword ptr [0x12345678]

### ISSUE THREAD

**Issue by Ben-Lichtman** [icedland/iced#198]
`call qword ptr [0x12345678]`, `jmp qword ptr [0x12345678]`, `bnd jmp qword ptr [0x12345678]` etc. all seem to have `Register::RIP` as their memory base, however if I understand it correctly, this should be None, or mabe DS (based off https://stackoverflow.com/questions/31211561/what-does-qword-ptr-hexvalue-mean-without-a-base-register)

**Comment by wtfsck** [comment]
There's a formatter option to show it as `[rip+xxx]` or the absolute value `[xxxxxxxxxxh]`, see `rip_relative_addresses` (set it to `true`).

**Comment by Ben-Lichtman** [comment]
Oh I see... That is a bit counter-intuitive. Will close this issue though
