### ISSUE TITLE
Add deprecated Intel KNC instructions

### ISSUE THREAD

**Issue by 0xd4d** [icedland/iced#2]

**Comment by evanrichter** [comment]
As a new contributor, what would it take to get this added? What docs or source from this project do you recommend I read to see if I am up for the task?

**Comment by 0xd4d** [comment]
First of all, it will probably be a lot of work. ;)

Docs: https://software.intel.com/sites/default/files/forum/278102/327364001en.pdf

It's probably a few hundred instructions.

The Generator project (C#) would need to be updated. Eg. decoder tables, formatter tables, etc.

These instructions also have swizzle/convert transformations so the Instruction would need at least one new property.

New decoder handlers would need to be added too to handle the new operands.

**Comment by evanrichter** [comment]
thanks for the fair warning :+1: 

I would only be able to help out on the rust side of things, unfortunately. Would that break the compatibility with the C# code if I only added features to the rust crate?

Also I won't be ready to start on this right away, I'm building out various other parts of my project first.

**Comment by 0xd4d** [comment]
> I would only be able to help out on the rust side of things, unfortunately. Would that break the compatibility with the C# code if I only added features to the rust crate?

This requires updating the C# generator project so if you want to fix this issue, you have to write some C# code.
