### ISSUE TITLE
Can I get the byte values for an instruction?

### ISSUE THREAD

**Issue by tibich72** [icedland/iced#202]
Hi, 

thank you for Iced, it is really impressive and fast.

Is Iced equipped to parse a string representation of an instruction (say "push edi") into an Instruction? I can build the "push edi" instruction by creating an assembler and then using 'assembler.push(edi)'. However, I'm starting from the textual representation of these instructions; I can write my own parser, but if there's one in place already, that would probably  be faster and more robust.

Thank you,
Tibi

**Comment by wtfsck** [comment]
No, there's no code that parses text and returns the bytes.

**Comment by tibich72** [comment]
Thank you for the information -- saved some searching/experimenting.
