### ISSUE TITLE
Equivalent to .long/.word directives in GAS?

### ISSUE THREAD

**Issue by ethindp** [icedland/iced#207]
What is the equivalent to directives like .long/.word/.byte/etc. in GAS? E.g.: this code:

```asm
    .align 16
_L8010_GDT_table:
    .long 0, 0
    .long 0x0000FFFF, 0x00CF9A00    ; flat code
    .long 0x0000FFFF, 0x008F9200    ; flat data
    .long 0x00000068, 0x00CF8900    ; tss
_L8030_GDT_value:
    .word _L8030_GDT_value - _L8010_GDT_table - 1
    .long 0x8010
    .long 0, 0
```

I know that there are methods like [db](https://docs.rs/iced-x86/1.15.0/iced_x86/code_asm/struct.CodeAssembler.html#method.db) and [dq_i](https://docs.rs/iced-x86/1.15.0/iced_x86/code_asm/struct.CodeAssembler.html#method.dq_i), but does that apply to a particular label, and how do you "align" them when creating them? I suppose I could just directly write the raw values to memory but that feels kinda like a hack.

**Comment by wtfsck** [comment]
The gas formatter uses these:

bits | masm/nasm | gas
-----|---------------|-----
8 | db | .byte
16 | dw | .word
32 | dd | .int
64 | dq | .quad

I don't know if `.long` is 32 or 64 bits.

`.dq()` and `.dd()` don't currently support labels. Adding support for it should be easy.

Alignment isn't supported at the moment.

**Comment by wtfsck** [comment]
> @wtfsck Thanks! The instructions I'm specifically concerned with are these:
> 
> ```assembly
> _L8040:
>     xorw    %ax, %ax
>     movw    %ax, %ds
>     lgdtl   0x8030
> ```

Those instructions don't have any `dq(label)` or align directives so should work today.

> How hard would it be to implement alignment?

Shouldn't be a problem.

> According to the [directives documentationsection](https://sourceware.org/binutils/docs/as/Align.html) AS by default pads data with zeros or NOPs. It might be a good idea to implement something like that for x86 specifically, though we might also want to consider just going for the semantics of [.balign](https://sourceware.org/binutils/docs/as/Balign.html) or [.p2align](https://sourceware.org/binutils/docs/as/P2align.html).

Both can be supported, `p2align` seems to be `b2align(1 << n)`

**Comment by ethindp** [comment]
@wtfsck How are label-level db/dw/dd/dq data arguments unsupported? Looking at the code I get the impression that declaring a label then using .dd()/.dw()/.dq()/... would work fine:

```rust
	#[allow(clippy::missing_inline_in_public_items)]
	pub fn db(&mut self, data: &[u8]) -> Result<(), IcedError> {
		self.decl_data_verify_no_prefixes()?;
		for bytes in data.chunks(CodeAssembler::MAX_DB_COUNT) {
			self.add_instr(Instruction::with_declare_byte(bytes)?)?;
		}

		Ok(())
	}
```

And the algorithm for `decl_data_verify_no_prefixes` simply checks if the data declaration has any prefixes, but declaring a label doesn't set any prefixes. Similarly, `add_instr()` doesn't clear the label until *after* the instruction(s) have been added, so theoretically this should work (excluding alignment), no?

```rust
let a = CodeAssembler::new(16)?;
let mut ap_trampoline = a.create_label()?;
a.cli()?.cld()?.jmp(0x8040)?; // Not quit the same as ljmp in GAS...
a.set_label(ap_trampoline)?;
let mut gdt_table = a.create_label()?;
a.dd(&[0, 0, 0x0000FFFF, 0x00CF9A00, 0x0000FFFF, 0x008F9200, 0x00000068, 0x00CF8900])?;
a.set_label(gdt_table)?;
```

The only thing that won't work is this part if I'm right:

```asm
_L8030_GDT_value:
    .word _L8030_GDT_value - _L8010_GDT_table - 1
    .long 0x8010
    .long 0, 0
```

And I don't know how the processor would take things if I used dd instead of dw for everything in that part, nor do I know how to simulate that calculation (I suspect it might be a memory calculation). Thoughts?
