### ISSUE TITLE
Use relative addressing in 64-bit assembler

### ISSUE THREAD

**Issue by 7x-hex-x7** [icedland/iced#209]
How can I use relative addressing in 64-bit assembler?

I have some code:
```
            long RIP = 0x13FF60000

            long bTest = RIP + 0x100;

            long pTestValue = RIP + 0x200;

            #region asm_01
            var asm_01 = new Assembler(64);

            //
            asm_01.cmp(__byte_ptr[rax + 0x08], 0x3A);
            asm_01.jne(asm_01.@F);
            asm_01.cmp(__byte_ptr[bTest], 0x01);
            asm_01.jne(asm_01.@F);
            asm_01.mov(ecx, __dword_ptr[pTestValue]);
```

As a result, it turns out like this:
```
13FF60000 - 80 78 08 01           - cmp byte ptr [rax+08],3A
13FF60004 - 75 11                 - jne 13FF60017
13FF60006 - 80 3C 25 0001F63F 01  - cmp byte ptr [3FF60100],01
13FF6000E - 75 07                 - jne 13FF60017
13FF60010 - 8B 0C 25 0002F63F     - mov ecx,[3FF60200]
```
That is, absolute addressing is used here, and the address is "truncated" to 32-bit.

But in another assembler it turns out like this:
```
13FF60000 - 80 78 08 01           - cmp byte ptr [rax+08],3A
13FF60004 - 75 11                 - jne 13FF60017
13FF60006 - 80 3D F3000000 01     - cmp byte ptr [13FF60100],01
13FF6000D - 90                    - nop 
13FF6000E - 75 07                 - jne 13FF60017
13FF60010 - 8B 0D EA010000        - mov ecx,[13FF60200]
13FF60016 - 90                    - nop 
```

Can I use relative addressing in Iced? Is it possible to make it so that instead of bytes of the CMP instruction **80 3C 25**, bytes **80 3D** are used, as in another assembler?

**Comment by vlacre** [comment]
> It's assumed to be an absolute address so that's why you get an error. Those instructions only take a signed 32-bit address and your address doesn't fit in an i32.
> 
> The current code uses `[rip+xyz]` if you try to reference a label but you can't do that here. Shouldn't be difficult to also support this case.
> 
> A workaround is to put the address in a 64-bit register first, `mov rax,0x123456789ABCDEF0; mov ecx,[rax]`.

So you won't be able to make relative addressing in Ised? :(
Гnfortunately the workaround with rax will not work, since I need to do this:
`mov [pTest],rbx`
that is, this way I will read the value from the register
