### ISSUE TITLE
Decoder that does not borrow slice of instructions.

### ISSUE THREAD

**Issue by i509VCB** [icedland/iced#218]
Hello, I've noticed an issue with the current `Decoder` struct when it comes to decoding instructions in the case of an interpreter.

When it comes to basic programs that write to a memory, it may be nessecary to write to a different part of memory that the decoder borrows a slice off somewhere else within the memory. This causes issues if you don't want to resort to undefined behavior via shared slice references or constructing a new decoder every time an instruction is run.

It would be nice if a decoder were available that decodes from a user provided slice of bytes, returning how many bytes were read to resolve the above.

**Comment by wtfsck** [comment]
Is it not possible to just pass in a smaller slice to the `Decoder`? Max instruction length is 15 bytes.

The total length it decoded can be found by calling `Instruction::len()`

**Comment by i509VCB** [comment]
I guess writing issues at 2am isn't always clear, so I'll rephrase.

The general process I follow for interpreting instructions:

```
loop {
    let ins = fetch_instruction_from_memory(cpu.ip, &memory);
    interpret_ins(&mut cpu, &mut memory, &ins);
}
```

In iced, this would expand to something more like:
```rust
// Just assume the slice into memory is a small segment based off the instruction pointer and 15-bits like said earlier, this is a quick example I wrote in github.
let decoder = Decoder::new(bitness, &memory[..], DecoderOptions::NONE);

for instruction in decoder {
    interpret_instruction(&mut cpu, &mut memory, &instruction);
}
```

Say the function `interpret_instruction` takes a mutable reference of the memory with the following signature:
```rust
fn interpret_instruction<const SIZE: usize>(cpu: &mut Cpu, memory: &mut [u8; SIZE], instruction: &Instruction) {
    unimplemented!("Implementation here")
}
```

Part of the decoder struct borrows some slice of memory to decode from. However the same memory needs a mutable references inside the interpreter itself. This makes rustc unhappy.

The following playground example presents the issue I have at the moment in a more simple form:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=01e6e0bdd6e8739a7e8624d27f29ef1c

Possible workarounds are quite bad:
- Construct a new decoder for each instruction
  - This has some bad overhead, mandating in a sense that I invoke what cargo asm says are 200+ x86 instructions to construct a new instruction every time.
- Construct one decoder and parse forward several instructions before dropping to execute.
  - Obviously jump instructions that go far enough will mean I need to stop what I am doing in execution and fetch again.
- Use undefined behavior
  - This would mean using something horrible like `ptr::slice_from_raw_parts` to modify under the slice iced borrows. This is bad since the use of the returned slice is unsafe. This is not acceptable of course.
- Copy the next group of instructions and decode from a copy.
  - Similar issue to one decoder parses several instructions but now with a memcopy.

Given the above issues I have encountered, the solution I see if a new decoder function, something like the following:
```rust
impl NewDecoderIdea {
    // Code to instantiate this would be like the existing Decoder but only taking bitness and decoder options.

    pub fn decode(&self, bytes: &[u8]) -> iced_x86::Result<Instruction> {
        unimplemented!("Implement me")
    }
}
```

The new decoder would allow me to temporarily lease the slice to the decoder to decode and then I can interpret without having an issue where the immutable borrow is still present.

**Comment by wtfsck** [comment]
Your solution would probably work.

I assume you need this for perf reasons?

A:

```
loop  {
  instr = decode
  interpret instr
}
```

vs

B:
```
loop {
  instrs = decode up to N instrs (stop early if eg. uncond branch etc)
  interpret instrs
}
```

A is your current code, and you mentioned B above in your workaround. Are you sure that A is faster than B?

Also if you use B, you could cache blocks of instructions, you can't do that with A.
