### ISSUE TITLE
Labels in disassembly

### ISSUE THREAD

**Issue by Kixiron** [icedland/iced#222]
Is it possible to add visible labels to the assembly generated by iced? I'd like to be able to see the portions of my generated code in a somewhat more readable fashion. For example, something like this:
```rust
let mut asm = CodeAssembler::new();
let mut thing = asm.named_label("something");

asm.push(rcx);
asm.jmp(thing);

asm.set_label(&mut thing);
asm.xor(rcx, rdx);
```
Producing this output
```asm
push rcx
jmp something

something:
  xor rcx, rdx
```
Instead of this
```asm
push rcx
jmp 0xF00DBEEF
xor rcx, rdx
```

**Comment by wtfsck** [comment]
At the moment, `CodeLabel`is just a `u64` with no label name at all. And if you assemble the stuff to bytes that info is completely removed (it's just bytes).

When are you formatting those instructions? Before or after calling `assemble()`?

**Comment by Kixiron** [comment]
I'm assembling it and *then* formatting it, but either workflow (instructions -> format  or instructions -> encode -> decode -> format) works for me

**Comment by wtfsck** [comment]
If you're formatting it after decoding the assembled bytes, then all labels have been erased (it's just bytes now).

You can call `instr.flow_control()` to get the control flow info to find all branches and mark those addresses as 'labels'. If the current instruction is at a label, print the label.

The interesting enum variants would be `FlowControl::UnconditionalBranch` and `FlowControl::ConditionalBranch`. Calling `instr.near_branch_target()` would give you the target address which should be marked as a label.

**Comment by Kixiron** [comment]
How would I connect a label address with a human readable name?

**Comment by wtfsck** [comment]
There's currently no API to get the address of a created label. I usually just disassemble the bytes and create labels such as `LBL_<N>` where labels are first sorted by address then they get N = index of label.
