### ISSUE TITLE
Implement `Hash` for register types

### ISSUE THREAD

**Issue by Kixiron** [icedland/iced#223]
Currently the various register types (`Register`, `AsmRegister8`, `AsmRegister64`, ...) don't implement `Hash`, which means they can't be stored within a `HashMap` or `HashSet` which limits some things you can do with them. Implementing `Ord` would also be nice, as it'd allow storing registers within `BTreeMap`s/`BTreeSet`s

**Comment by wtfsck** [comment]
PR welcome!

The registers are generated by this file: https://github.com/icedland/iced/blob/master/src/csharp/Intel/Generator/Assembler/Rust/RustAssemblerSyntaxGenerator.cs
