### ISSUE TITLE
RCX Conditional jumps have IsJccShort set to false

### ISSUE THREAD

**Issue by am0nsec** [icedland/iced#225]
At the moment the code set `IsJccShort` class member from `Instruction` class to `true` when the following condition is met (in `InstructionInfoExtensions.cs`): 
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static bool IsJccNear(this Code code) =>
	(uint)(code - Code.Jo_rel16) <= (uint)(Code.Jg_rel32_64 - Code.Jo_rel16);
```

However, this is omitting the three conditional jump instructions when CX/ECX/RCX register is equals to zero. A fix would be to extend the expression, as follows:
```csharp
[MethodImpl(MethodImplOptions.AggressiveInlining)]
public static bool IsJccNear(this Code code) =>
	(uint)(code - Code.Jo_rel16) <= (uint)(Code.Jg_rel32_64 - Code.Jo_rel16) ||
	(uint)(code - Code.Jcxz_rel8_16) <= (uint)(Code.Jrcxz_rel8_64 - Code.Jcxz_rel8_16);
```

Additionally, it is not not related to this issue but it may be useful to add a new `ConditionCode` enum member for when the condition is that CX/ECX/RCX is equals to zero. It will be useful for the aforementioned instructions but also for the `LOOP` and `LOOPcc` instructions, for example.

**Comment by wtfsck** [comment]
That method was never meant to return true for `jrCX` instructions. Maybe it's confusing though.

Changing the behavior now could be a breaking change.

Maybe we could add a new method/property that returns true if it's jcxz/jecxz/jrcxz? Then you could just test 'is-jcc or is-jcx'

**Comment by am0nsec** [comment]
This is most likely the safest way I think. I was also thinking about something similar for `IsLoopShortConditional`, `IsLoopShortUnconditional` or just `IsLoopShort` (did not found a way to find whether the instruction is a loop or not). 

Happy to submit a PR for `IsJcxShort` -- and the others for loop if you are ok with it -- in the C# version of the code. My apologises, I have no Rust knowledge.

**Comment by wtfsck** [comment]
Sure, I can fix the Rust code and add tests later.

For consistency, the loop properties/methods should be called `IsLoopcc` (`loope`/`loopne`) and `IsLoop` (`loop`) (the last one is the unconditional one).

**Comment by am0nsec** [comment]
I added the aforementioned `IsJcxShort`, `IsLoop` and `IsLoopcc` functions. I also added unite tests in the `MiscTests.cs` for these members.
