### ISSUE TITLE
Can't write code generically over `CodeAssembler`

### ISSUE THREAD

**Issue by Kixiron** [icedland/iced#231]
All of `CodeAssembler`'s methods use generated traits (`CodeAssembler::mov()` has the `CodeAsmMov` trait, for instance) but these traits aren't public, making it impossible to write generic functions over an assembler, e.g.
```rust
struct MyCodeGenerator(CodeAssembler);

impl MyCodeGenerator {
    fn mov_but_better<T, U>(&mut self, dest: T, src: U) {
        self.0.mov(dest, 0);
        self.0.add(dest, src);
    }
}
```
These functions should be perfectly doable, but since the associated traits that act as bounds for the assembler methods aren't public there's no way to satisfy the bounds generically, causing compile errors

**Comment by wtfsck** [comment]
Yes that could be useful. Want to send a PR?

**Comment by Kixiron** [comment]
Sure, could you point me where I should make this change?

**Comment by wtfsck** [comment]
Making one (or more?) of these `pub` will probably work, didn't test it.

https://github.com/icedland/iced/blob/1b9aca03a797193925f8005d5dd82a420c44b369/src/rust/iced-x86/src/code_asm.rs#L19-L21
