### ISSUE TITLE
`Instruction::ip()` and `Instruction::len()` are never set by `CodeAssembler`

### ISSUE THREAD

**Issue by Kixiron** [icedland/iced#232]
The instructions generated by `CodeAssembler` never have their `.ip()` or `.len()` (and probably other informational methods) set, nor are there method(s) to calculate information for the current instruction or instructions within a `CodeAssembler`

**Comment by wtfsck** [comment]
Could you explain why you need them initialized? The assembler assembles the instructions and you get bytes. Decoding the bytes could be a solution.

**Comment by Kixiron** [comment]
I'd like to be able to print out some information about the code I've assembled, things like instruction sizes and being able to associate arbitrary instruction locations with data (thing adding comments to things or something along those lines)

**Comment by wtfsck** [comment]
The problem is that some instructions (branches) can be optimized, eg. if you add a `JE SHORT X`, it could generate `JE NEAR X` or some other instruction(s) if the target is very far away (>2GB). In that case, the instruction doesn't have a size since something else was generated.
