### ISSUE TITLE
`CodeAssembler` doesn't implement basic traits

### ISSUE THREAD

**Issue by Kixiron** [icedland/iced#233]
This looks to be on purpose due to the `#[allow(missing_debug_implementations)]`, but some basic `Debug`, `Clone` and `PartialEq` implementations would still be nice

**Comment by wtfsck** [comment]
Yes I usually don't derive Debug if it's some struct like Decoder or in this case CodeAssembler since it doesn't seem very useful. Their output (eg. Instruction) makes more sense to impl Debug.

Could you explain why PartialEq would be useful, and also why not Eq.

**Comment by Kixiron** [comment]
Well Debug (custom or derived, your call) is just generally useful. As for equality, I'm not sure where it'd actually go but I'd like to be able to utilize ices for code generation and optimization, so ideally I could look at multiple blocks and tell if they're equal in order to unify them. For PartialEq vs Eq that's also up to you as to whether or not equality between stuff is reflexive, symmetric and transitive (which I'd imagine it would be)

**Comment by wtfsck** [comment]
`Eq`: is it not enough to just compare the instructions, you can call `instructions()` to get a `&[Instruction]` which impl `Eq`

**Comment by Kixiron** [comment]
That's fair, implementing it allows things containing it to implement it as well though. In the end, up to you

**Comment by wtfsck** [comment]
If they have a `CodeAssembler` as a field, they can still impl `Eq, PartialEq` manually though.
