### ISSUE TITLE
wrong operand type

### ISSUE THREAD

**Issue by sha0coder** [icedland/iced#234]
This jmp instruction has one  operand detected as Register, but really it's Immediate.

```
1 0x3c0000: jmp       003C00FDh         (e9 f8 00 00 00)

println!("{} operands", ins.op_count());          // 1 operands

println!("{:?}", ins.op1_kind());   //  Register
```

and enters on  OpKind::Register match case instead of OpKind::Immediate  then the   info.used_registers() logically don't detect any register.

it was initialized in this way:
```rust
let mut decoder = Decoder::with_ip(32, &block, self.regs.eip as u64, DecoderOptions::NONE);
```

**Comment by wtfsck** [comment]
The operand kinds are zero-based, so try `op0_kind()`. They used to be 1-based but I found that to be too much problem when using for loops and passing in the index (it's easy to forget to do `i + 1`).

**Comment by sha0coder** [comment]
oh cool, then is not an issue, thanks.
