### ISSUE TITLE
readme being included into rust's lib.rs will fail doc tests

### ISSUE THREAD

**Issue by i509VCB** [icedland/iced#243]
CI won't fail because the doc test for the Readme is not tested.

I believe the solution to this is to add the nessecary imports in the Readme examples. Generally in rust we would prefix with a `# ` to hide something from the doc generator but still use it in compilation.

**Comment by wtfsck** [comment]
Which one of the examples fails? AFAIK, all examples import (`use`) everything they need so should compile, except the example that depends on the `colored` crate to print colored text to the console.

**Comment by i509VCB** [comment]
I'll check this when I am at my machine again. I ran `cargo test --doc` on the latest rustc but will test again with the msrv as well.

**Comment by wtfsck** [comment]
It's probably the `code_asm` feature example that failed. Try with `--features code_asm` and it should compile.
