### ISSUE TITLE
Encoder fails with 0x7f jump

### ISSUE THREAD

**Issue by jeremybeaume** [icedland/iced#249]
Hi, I thik I found a bug in the `Encoder` (in python):
```python
ins = list(Decoder(32, b'\x67\x78\x7f', ip=0x00400000))[0] # js short 0x7f
encoder = Encoder(32)
encoder.encode(ins, ins.ip)
print(encoder.take_buffer().hex())
```

which gives :
```
ValueError: Branch distance is too far away: next_ip: 0x00400002 target: 0x00400082, diff = 128, diff must fit in an i8
``` 

If next_ip was indeed `0x004000002`, the jump is indeed to small to be encoded. But, hte instruction is 3 byte long, meaning next_ip is `0x00400003`, and the jump is only 127 bytes, which should work.

What I don't understand is that both next_ip and len are correct :
``` python
ins = list(Decoder(32, b'\x67\x78\x7f', ip=0x00400000))[0] # js short 0x7f
print(ins.len)
print(hex(ins.next_ip))
```
```
3
0x400003
```

The encoder seems to compute `next_ip` again, and fails to do so properly, which then gives it a bad value for the relative jump, too big for a single byte.

Technical details :
iced version : 1.15.0 (pip)
python version : 3.8.10 (Ubuntu 20.04.3 LTS)

Good luck fixing it if it is indeed a bug 👍

**Comment by wtfsck** [comment]
Your decoded instruction has a useless `67h` prefix. When the encoder tries to encode it, it doesn't add the useless prefix so it's encoded as a 2-byte instruction. But that also means the target is now 128 bytes after the new encoded instruction's 'next ip' so it fails to encode it.

Remove the 67h prefix and it should work. Or you can just use `BlockEncoder` which will optimize branches so you don't have to think about short and near branches.

**Comment by jeremybeaume** [comment]
I see, I'll check that out then ! Thanks a lot for the lightning fast answer !
