### ISSUE TITLE
Revert rustc 1.61 + wasm-bindgen + big enum workaround commit

### ISSUE THREAD

**Issue by wtfsck** [icedland/iced#298]
Revert https://github.com/icedland/iced/commit/dc901cfe22b9bc725438456ce66bd29af05ec679 when https://github.com/rust-lang/rust/issues/97222 is fixed.

**Comment by clubby789** [comment]
The code that caused the crash seems to compile successfully now, so it may be safe to revert this.

**Comment by wtfsck** [comment]
Seems like it was fixed in 1.65.0 (current release is 1.66.0).
