### ISSUE TITLE
Replacing nasm

### ISSUE THREAD

**Issue by AnErrupTion** [icedland/iced#309]
I want to get rid of nasm in my project to use Iced instead (C#). However, I also rely on the ``-felf64`` nasm argument. And, as far as I know, iced is not able to generate ELF object files.

So my question is: are there any plans to make such thing, and if not, are there alternatives (a separate library that I can use after assembling my code with Iced) to do such thing?

Kind regards,
AnErrupTion

**Comment by wtfsck** [comment]
No there are no plans to support writing elf files or other executable files.
