### ISSUE TITLE
Revert (some) const functionality from #296

### ISSUE THREAD

**Issue by clubby789** [icedland/iced#323]
While marking functions as `const` in the PR (#296), I didn't notice a few issues, such as https://github.com/icedland/iced/blob/84fa85b2417a1ea84044a70c1775e94bcce0df62/src/rust/iced-x86/src/decoder.rs#L1247-L1251

Comparing pointers in a `const` context is [disallowed](https://github.com/rust-lang/rust/issues/53020) without unstable features, but since the pointers are stored as `usize`, rustc didn't warn of the issue.

There might be other functions that shouldn't be `const`, this is just the first one I noticed.

**Comment by wtfsck** [comment]
There are only 6 `const fn` in that file, so seems like you found the only function that shouldn't be const. Want to send a PR?
