### ISSUE TITLE
code_asm: `CodeAssembler` docs.rs page causes Chrome page crash

### ISSUE THREAD

**Issue by clubby789** [icedland/iced#351]
Accessing https://docs.rs/iced-x86/latest/iced_x86/code_asm/struct.CodeAssembler.html causes my Chrome tab to crash after a few seconds of rendering the page (the page renders fine on Firefox). This can make looking up methods on the `CodeAssembler` pretty tricky without resorting to source code reading.

I'm not sure what could be done to improve the experience, but wanted to note this down as an issue I'd experienced. Adding `<style>details { content-visibility: auto }</style>` to the page head makes the page usable but I'm unsure if custom styles are possible on docs.rs without upstream support.

**Comment by wtfsck** [comment]
I've noticed that too. Chrome seems to be really slow when there's a lot of text. Firefox works great.

**Comment by clubby789** [comment]
Might be addressed by https://github.com/rust-lang/rust/pull/102253 - I provided this page as an example of one which has its performance improved by the CSS changes.

**Comment by clubby789** [comment]
I'm able to load the page, scroll pretty fluidly, use Ctrl-F etc. so this looks to be pretty usable now
