### ISSUE TITLE
Add missing instructions

### ISSUE THREAD

**Issue by Symbai** [icedland/iced#357]
Instructions Intel added in September this year seem to be missing:

```
AADD
AAND
AOR
AXOR
RDMSRLIST
VBCSTNEBF162PS
VBCSTNESH2PS
VCVTNEEBF162PS
VCVTNEEPH2PS
VCVTNEOBF162PS
VCVTNEOPH2PS
VCVTNEPS2BF16
VPDPB[SU,UU,SS]D[,S]
VPMADD52HUQ
VPMADD52LUQ
WRMSRLIST
WRMSRNS
```

**Comment by wtfsck** [comment]
I think there are couple more instructions, eg. CMPccXADD, TDPFP16PS etc.

Also there's a new AMD instruction. `RMPQUERY F3 0F 01 FD`
