### ISSUE TITLE
Implement `is_ret_near()` and `is_ret_far()`.

### ISSUE THREAD

**Issue by vext01** [icedland/iced#366]
E.g. there is a `is_call_near()` but not a `is_ret_near()`.

Cheers.

**Comment by wtfsck** [comment]
Makes sense. PRs accepted.

**Comment by vext01** [comment]
Thank you!

**Comment by wtfsck** [comment]
No, I didn't write any code. No-one wanted to implement the feature and this issue is almost 4 months old so it was closed.
