### ISSUE TITLE
Publishing Java artifact to Maven repository

### ISSUE THREAD

**Issue by Col-E** [icedland/iced#376]
It would be very handy as a developer to have iced available as a maven artifact so it could be easily added to any maven/gradle project. Maven central would be ideal, but any host is better than no host. This could be done as part of the automated GH actions process.

**Comment by Col-E** [comment]
Oh, this is apparently already in the works: https://s01.oss.sonatype.org/#nexus-search;quick~iced-x86

**Comment by wtfsck** [comment]
Yes the release CI yaml file uploads it to maven central now.

For some reason it's not showing up when I search though: https://mvnrepository.com/search?q=iced-x86 (I didn't check all pages)

**Comment by Col-E** [comment]
Sometimes the search services do not reflect what is actually on the target repo's. Checking manually, I don't see `io.github.icedland.iced` on central: https://repo1.maven.org/maven2/io/github/

**Comment by wtfsck** [comment]
Maybe because it has -SNAPSHOT in the filename?

**Comment by Col-E** [comment]
That would make sense, since I believe they do try and separate between their official releases/snapshots on different repositories. Worth a try to see if the suffix is the problem.

**Comment by wtfsck** [comment]
Yeah I'll try to re-do it next year. ;)

**Comment by wtfsck** [comment]
The non -SNAPSHOT version got uploaded yesterday: https://central.sonatype.dev/artifact/io.github.icedland.iced/iced-x86/1.18.0
