### ISSUE TITLE
Force JMP to emit near instead of short?

### ISSUE THREAD

**Issue by pellsson** [icedland/iced#409]
I've done some mediocre source diving; am I correct in understanding that I can't force iced to emit a near jmp (including jccs)? It will pick a short if short is close enough correct?

Would be cool if I could force a near. Maybe have a different constants like Code.JXX_NEAR32_64?

**Comment by wtfsck** [comment]
Are you using the assembler or block encoder? If so you can disable optimizing branches.

**Comment by pellsson** [comment]
Hi :) I am using the block one (under Python if that has significans) but it should be very easy to switch. Which one has the ability to disable?

Also this library is so well written and such a pleasure to work with. Very good job <3

**Comment by wtfsck** [comment]
When creating the BlockEncoder you can pass in fix_branches = False to disable that optimization.

```py
	### Args:

	- `bitness` (int): 16, 32 or 64
	- `fix_branches` (bool): (default = `True`) Fix branches (eg. convert short to near branches if the target is too far away)
```
