### ISSUE TITLE
[C#] How do you write `mov rax, gs:[60h]`

### ISSUE THREAD

**Issue by unkusr007** [icedland/iced#414]
I can't find the right way to write it, I looked into the documentation and past issues, and it has never been mentioned.
Sorry if I missed something.

**Comment by wtfsck** [comment]
Something like this should work if you're using the `Create()` methods:

```C#
Instruction.Create(Code.Mov_RAX_moffs64, Register.RAX, new MemoryOperand(Register.None, 0x60, 8, false, Register.GS))
```
