### ISSUE TITLE
Having Trouble Building C#

### ISSUE THREAD

**Issue by dr-NHA** [icedland/iced#425]
It Wont Let Me Build With NetStandard Only .Net 7
Please Let Me Know :)

**Comment by wtfsck** [comment]
The nuget package supports net45 netstandard 20 and 21 so if you target one of the netstandards or anything that supports those netstandards, it should build fine.

If not, provide more info, repro steps etc.

**Comment by dr-NHA** [comment]
Lol Its Issue Is Not "Completed"
I Still Havent Compiled The Binary Myself,
Maybe You Can Link A Tutorial Or Show Me?
As I Dont Want To Use A Nuget Package I Want To Use The Source
