### ISSUE TITLE
Undefined behavior in Rust crate?

### ISSUE THREAD

**Issue by cblichmann** [icedland/iced#429]
Hey all,

As part of a quick review of the various downstream dependencies of Cloud Hypervisor, one of my coworkers had a look at the use of `unsafe` in the iced-x86 Rust crate. \
I have since landed a PR in Cloud Hypervisor that make this crate optional on Linux and KVM, but I think the results of the review might still be useful:

> The Rust crate has more than 600 unsafe blocks, and while there are patterns they are not easy to verify for correctness due to the invariants being upheld non-locally, and a lot of it is one-off. For a bunch of things (e.g. the 300 decoder handler unsafe blocks in vex.rs and elsewhere) safe abstractions should be defined.
>
> There is at least one class of instances of UB: All of the transmutes in `factory.rs` assume a layout of `#[repr(Rust)]` enums. This would be fixed by using `repr(u8)` instead. Plus the the 43 `unsafe {}` blocks could also be reduced down to one unsafe block using an abstraction around `TABLE`. This UB is unlikely to actually be problematic.
>
> Consider using open enums (https://docs.rs/open-enum) instead of closed enums so that you don't have to worry about transmute safety. A lot of these things aren't being matched anyway. If the exhaustiveness is desirable, consider using https://docs.rs/int-enum/ instead. Avoid relying on action-at-a-distance conditions where a transmute is asserted ok because "the data is valid", unless it actually does matter for perf. \
> `TABLE` should return some typedef which has methods that perform all the unsafe transmutes that are currently being performed on its data assuming that it is valid. These methods should mention the area of the codegen code that upholds the right invariants.
The decoder handler unsafes can be reduced to a single unsafe where you have a `HandlerFunction(fn(*const c_void, &Decoder, &Instruction), *const c_void)`, which has a safe `.handle(decoder, instruction)` method and a safe `fn new<T: 'static>(handler: T, fn: fn(&T, &Decoder, &Instruction)`.

While I did look into this myself, I don't feel familiar enough with the codebase (and its C# codegen) to create a pull request.

**Comment by wtfsck** [comment]
The enums are fieldless enums (i.e., like C and C++ enums) so the Rust compiler is guaranteed to use only integers. Eg. the
first one gets the value 0 unless the programmer overrides it, the next one gets the value 1 (unless the programmer overrides it) etc.

If the size of the enum value and the data passed to transmute aren't the same size, that's a compilation error. Eg. trying
to transmute a u16 to an enum that the compiler decided should use a u8 is a compilation error. If a future compiler decided to
use oversized enum values eg. u32 for everything, then trying to convert that u16 value with transmute is also a compilation error.

Here's a Rust playground link with an example. You can click the Tools button and then on Miri to see if
it detects any UBs in those transmutes (it doesn't). If you then enable the bad code at the bottom of the
function and try miri again, it will detect the bad convert from `123u8` to the enum showing that it's possible
for miri to detect this condition.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=57d8898bdd6abd054b78e8f507083b92

Those transmutes are converting generated data (stored in read-only memory) to enums. They're similar to the code in the Rust playground (i.e., pass in a valid value and you're guaranteed to get back a valid Rust enum value).

The rest of the comments don't mention any UBs and seems to be more of a code review.

**Comment by wtfsck** [comment]
Closing it, since it's been answered and there are no more questions. Let me know if you want me to reopen it.
