### ISSUE TITLE
[Question] Is `try_immediate()` meant for public use?

### ISSUE THREAD

**Issue by mbbutler** [icedland/iced#437]
I have found that the `try_immediate()` function is extremely convenient for reducing boilerplate match arms when performing some light emulation during disassembly. However, it has the `#[doc(hidden)]` attribute which suggests it is not meant to be publicly exposed.

Is this function intended to be used by the public or should I not be using it?

**Comment by wtfsck** [comment]
Yes it's not meant to be public API, however if it's useful it can be made public (with docs). Do you want to send a PR (just add docs and remove both attributes)?

**Comment by mbbutler** [comment]
I'll get started on a PR now. Thank you for the quick response.
