### ISSUE TITLE
Formatting hex values different from memory addresses

### ISSUE THREAD

**Issue by lordmilko** [icedland/iced#445]
Generally speaking, when formatting disassembly, I want to include a `h` suffix on hexadecimal numbers

```
mov     ecx,dword ptr [ebp-14h]
push    24h
```
however, when it comes to displaying values we can know for certain are *memory addresses* (specifically, displaying a symbol's address), I want to to display these values without a trailing suffix, such that it looks just like the intellisense example on the `FormatterOptions.ShowSymbolAddress` property

![image](https://github.com/icedland/iced/assets/6138789/0acd3600-2d09-4f63-99ba-9ba0de378550)

Unfortunately, it appears these two options are mutually exclusive. If a suffix is set for any numbers, it is set for all numbers. Thus instead of the following
```
call    ntdll!NtQueryInformationProcess (77de62e0)
```
I get
```
call    ntdll!NtQueryInformationProcess (77de62e0h)
```
 There don't appear to be any hooks I can leverage before the symbol address is written that I can leverage to change the formatting behavior of the symbol address.

I thought that maybe I could hack my `ISymbolResolver` to return the symbol *and* address appended after it, however in-between the symbol and symbol and symbol address being written there is [a whole bunch of stuff](https://github.com/icedland/iced/blob/2df7533a73307125cd983da00d422aa86fc6a81e/src/csharp/Intel/Iced/Intel/FormatterOutput.cs#L94-L126) relating to displaying the symbol displacement. If I were to lie about the address of the resolved symbol, and handle combining the symbol + displacement + symbol address in my resolver myself and returning that merged string as "the symbol", this would probably work, but it's not exactly a great solution.

Do you have any thoughts on this and/or whether this is something Iced can be made to accommodate?

**Comment by lordmilko** [comment]
A related issue is that the displacement you get also follows the default formatting

```
je      notepad!__report_gsfailure+1ch
```
but I would want to have a `0x` prefix and no suffix as follows
```
je      notepad!__report_gsfailure+0x1c
```

**Comment by wtfsck** [comment]
You can override the number formatter options per operand by passing in a `IFormatterOptionsProvider` to the formatter ctor but it seems like you want different options per number even if they're in the same operand. That's not possible. Your workaround above probably works.

Another one is to use a regex and fix it after it has formatted the whole instruction or just one operand (see `FormatOperand(in Instruction instruction, FormatterOutput output, int operand)`).

**Comment by lordmilko** [comment]
I've implemented a `FormattedSymbolProvider : ISymbolProvider` that wraps a normal `ISymbolProvider` and adjusts the resulting `SymbolResult.Text` to merge the `Text` `Address` and effective displacement all together with the desired formatting. This seems to work well.

Ostensibly, Iced could support such formatting natively by adding the following `FormatterOptions` properties

* `SymbolHexPrefix`
* `SymbolHexSuffix`
* `SymbolDisplacementHexPrefix`
* `SymbolDisplacementHexSuffix`

(there are already existing settings referring to other types of "displacement", hence the need to say "SymbolDisplacement" here)

As Iced supports a hodgepodge of other formatting options I think these would be good options to have, however as my issue has been resolved I will close this issue
