### ISSUE TITLE
66h prefixed jmp is disassembled incorrectly resulting in bogus instructions in 32-bit mode.

### ISSUE THREAD

**Issue by MulleDK19** [icedland/iced#468]
Prefixing E9 00 00 00 00 with 66 causes 66 E9 00 00 00 00 00 00 to be disassembled as

0x140000000: 66 E9 00 00 - jmp 4
0x140000004: 00 00           - add byte ptr [eax], al
0x140000006: 00 00           - add byte ptr [eax], al

instead of the correct
0x140000000: 66 E9 00 00 00 00 - jmp 0x140000004 (ignored prefix)
0x140000006: 00 00                     - add byte ptr [eax], al

This is further complicated by the fact that AMD respects the prefix, while Intel ignores it, but I think it's more important to handle it like Intel does, and not allow it to be used to hide instructions at the now invalid decoding offset.

**Comment by wtfsck** [comment]
There's a `DecoderOption.AMD` that can be used to decode some instructions the way AMD does it. Pass it in to the decoder.

**Comment by MulleDK19** [comment]
> There's a `DecoderOption.AMD` that can be used to decode some instructions the way AMD does it. Pass it in to the decoder.

But the problem is that the above *is* the way AMD does it. Intel ignores the prefix and executes it as a regular E9 00 00 00 00, while Iced will decode it as 66 E9 00 00 and produce the incorrect AMD interpretation.

**Comment by wtfsck** [comment]
Do you have a small repro?

**Comment by MulleDK19** [comment]
> Do you have a small repro?

```csharp
private static void JmpPrefixBug()
{
    byte[] data = new byte[] { 0xe9, 0xfb, 0x0f, 0x05, 0x00, 0x0F, 0x0B, 0xB8, 0x00, 0x50, 0x40, 0x00, 0xFF, 0xD0 };

    for (int i = 0; i < 2; i++)
    {
        Console.WriteLine(i is 0 ? "Non-prefixed:" : "Prefixed:");
        ByteArrayCodeReader r = new ByteArrayCodeReader(data);
        Decoder decoder = Decoder.Create(32, r, 0x401000ul, DecoderOptions.None);
        for (int j = 0; ; j++)
        {
            Instruction instruction;
            decoder.Decode(out instruction);
            if (instruction.IsInvalid)
            {
                break;
            }

            string bytes = string.Join(" ", data.Skip((int)(instruction.IP - 0x401000ul)).Take(instruction.Length).Select(b => b.ToString("X2"))).PadRight(3 * 5);
            Console.Write($"<{instruction.IP:X8}> {bytes} {instruction}");
            if (i is 0 && j is 0) Console.Write("  Imagine 452000h is a jmp to 401007h");
            if (i is 1 && j is 0) Console.Write("  Intel ignores the 66 prefix and decodes it as 66 E9 00 00 05 00, and it behaves as a non-prefixed jump.");
            if (i is 1 && j is 1) Console.Write("  Iced parses it like AMD and is now reading at the wrong offset, hiding the actual instructions. Intel runs the code exactly like the non-prefixed above.");

            Console.WriteLine();
        }

        if (i is 0)
        {
            data = new byte[] { 0x66 }.Concat(data).ToArray();
            Console.WriteLine();
        }
    }
}
```

**Comment by wtfsck** [comment]
I can't test that yet, but do you have a minimal repor, something like:

```pseudo code
decoder = Decoder.create(64, "data", options);
decoder.decode()
check lenght here
```

**Comment by wtfsck** [comment]
Looking at your code, you're not decoding in 64-bit mode. Do you have any evidence that AMD or Intel ignores the 66 prefix in 16 or 32-bit modes?

**Comment by MulleDK19** [comment]
> Looking at your code, you're not decoding in 64-bit mode.
The prefix is ignored entirely in 64-bit mode, and the bug isn't present there.

> Do you have any sources that say that AMD or Intel ignore the 66 prefix in 16 or 32-bit modes?
Running the code it's clear that it's a regular jump; and https://youtu.be/KrksBdWcZgQ?t=1821

**Comment by wtfsck** [comment]
That video is showing a 64-bit disassembly, see the 'rsp' register.

Intel and AMD docs don't mention that 66 is ignored in 16 or 32-bit modes. It's only in 64-bit mode where AMD and Intel differ in how they decode some instructions.

**Comment by wtfsck** [comment]
Closing this, Intel and AMD use the 66h prefix in 16 and 32-bit modes.
