### ISSUE TITLE
Branch Instructions Fail on Underflow/Overflow

### ISSUE THREAD

**Issue by Sewer56** [icedland/iced#498]
# Description

When assembling the `jmp`/`jcc` opcode that overflows or underflows, the library throws an error, as opposed to correctly assembling the instruction.

Bug introduced in ceaf250b48a1d97ea2ab79d979636f760ee44741 

## Reproduction 

C#:
```csharp
using Iced.Intel;

var assembler = new Assembler(32);
assembler.jmp(0xFFFFFF00);
assembler.Assemble(new StreamCodeWriter(new MemoryStream()), 0);
```

Rust:
```rust
#[cfg(test)]
mod tests {
    use iced_x86::{code_asm::CodeAssembler, IcedError};

    #[test]
    fn use_assembler() -> Result<(), IcedError> {
        let mut a = CodeAssembler::new(32)?;
        a.jmp(0xFFFFFF00)?;
        let _bytes = a.assemble(0)?;
        Ok(())
    }
}
```

**Comment by wtfsck** [comment]
Thanks for the report, I'll have a look at it.

**Comment by Sewer56** [comment]
Found some additional interesting cases, where branches that overflow/underflow are not fully optimized.

```rust
#[rstest]
// Encodes as `e9ebffffff` which is correct, but unoptimal.
#[case((u32::MAX - 0xF) as isize, "ebee", 0)]
fn jmp_relative_x86(
    #[case] offset: isize,
    #[case] expected_encoded: &str,
    #[case] pc: usize,
) -> Result<(), IcedError> {
    let mut a = CodeAssembler::new(32)?;
    a.jmp(offset as u64)?;
    let bytes = a.assemble(pc as u64)?;
    assert_eq!(expected_encoded, hex::encode(bytes));
    Ok(())
}

#[rstest]
// Should not fail
#[case((usize::MAX - 0x7FFFFFFF) as isize, "e9ebffffff", 0)]
// Off by instruction length (5) error somewhere, as this works fine with 5 distance less. (0x7FFFFFFA)
#[case((usize::MAX - 0x7FFFFFFA) as isize, "e900000080", 0)]
#[cfg(target_pointer_width = "64")]
fn jmp_relative_x64(
    #[case] offset: isize,
    #[case] expected_encoded: &str,
    #[case] pc: usize,
) -> Result<(), IcedError> {
    let mut a = CodeAssembler::new(64)?;
    a.jmp(offset as u64)?;
    let bytes = a.assemble(pc as u64)?;
    assert_eq!(expected_encoded, hex::encode(bytes));
    Ok(())
}
```

Full Reproduction (ZIP)
[repro-rs-2.zip](https://github.com/icedland/iced/files/13723005/repro-rs-2.zip)

Due to GitHub size limits, I had to remove `.git` folder for Iced, the code there is of commit, ba7b92d1f11a9f78884cf4a749883bd148e50783 (last commit before bug introduced).

Might be worth checking once the main issue is resolved.

**Comment by wtfsck** [comment]
That `e9ebffffff` test case seems to be wrong, did you copy the wrong 'expected_encoded' value?

e9ebffffff case:

try to encode:

jmp 0FFFFFFFF80000000h

at offset 0.

You assume the result becomes e9ebffffff = jmp 0FFFFFFFFFFFFFFF0h and not jmp 0FFFFFFFF80000000h .

**Comment by Sewer56** [comment]
Seems you're correct, I must have been very tired at the time. It's what coding 24/7, during and after work does to you 😅

I must have copied this incorrectly when transferring over tests to the repro for experimenting.
