### ISSUE TITLE
Feature request: Improve resolving near indirect JMPs

### ISSUE THREAD

**Issue by Symbai** [icedland/iced#54]
Input:
`FF 25 00 00 00 00 00 00 66 DB 60 02 00 00`

IP = 0x1807AAA0000
Bitness = 64
Mode = NASM / MASM

Iced:
```
jmp       qword [rel 1807AAA0006h]
add       [rax],al
(bad)
add       al,[rax]
(bad)
```
Expected:
`jmp       far ptr 260DB660000h`
alternatively:
`jmp       qword [rel 1807AAA0006h]`
but store the target address 0x260DB660000 in a property. Also consider the following  `00 00 66 DB 60 02 00 00` to be part of the instruction.

**Comment by 0xd4d** [comment]
That is a near indirect branch, not a far branch.

Interpreting the instruction and the data that follows it as one instruction is better left to some higher level library or application.
