### ISSUE TITLE
`call qword ptr [2234h]` should probably be written as `call qword ptr [<something>+2234h]`

### ISSUE THREAD

**Issue by JohnScience** [icedland/iced#540]
I have little knowledge of assembly but I got confused when I saw a small hardcoded value in brackets, which is meant to be an address in `0x1800....` for `x86_64` DLl.

The address seems to be RIP-relative.

**Comment by JohnScience** [comment]
Doing this:

```
if instr.code() == iced_x86::Code::Call_rm64 {
            let target = (fn_ptr as u64).wrapping_add(instr.memory_displacement64());
            println!("\t; Target: {:#x}", target);
        }
```

Seems to work properly at least for one case.

**Comment by wtfsck** [comment]
It shows the absolute address by default. If you wnat to see rip+xxx, there's a formatter option you can enable/disable.

**Comment by JohnScience** [comment]
> It shows the absolute address by default. If you wnat to see rip+xxx, there's a formatter option you can enable/disable.

It's probably a poor default because if we don't specify instruction pointer, it displays the incorrect value.

**Comment by wtfsck** [comment]
It's an address relative to the current IP so make sure you set the correct IP when decoding and it should decode and format correctly.
