### ISSUE TITLE
Wrong op access on Sub_rm16_r16

### ISSUE THREAD

**Issue by thug-shaker** [icedland/iced#549]
Instructions with code Sub_rm16_r16 have op0_access() set to Write and all other operands to None.

**Comment by thug-shaker** [comment]
![image](https://github.com/icedland/iced/assets/130842565/dc979e14-cc5b-4be1-a576-263d2474b470)

**Comment by thug-shaker** [comment]
also exist on Sub_rm8_r8 as shown in the picture, only seems to happen when both operands are the same

**Comment by thug-shaker** [comment]
Seems to be when both operands are the same, I guess this is because it zeroes the reg. Some clarification would be appreciated. Closing for now.

**Comment by wtfsck** [comment]
It's because it's an xor reg,reg instruction. The result is always 0, so it's just a write 0 to the destination register, no input needed.
