### ISSUE TITLE
Register BPL is not between AL and BH (inclusive)

### ISSUE THREAD

**Issue by Symbai** [icedland/iced#559]
I get an exception `Register BPL is not between AL and BH (inclusive)` when I try to assemble `mov bpl,27`. It works fine using a different assembler. (Same with `SPL`, `SIL` and `DIL`). Is this a bug or am I doing something wrong?

```C#
var assembler = new Iced.Intel.Assembler(32);
assembler.mov(bpl, 0x27);
var ms = new MemoryStream();
var codeWriter = new Iced.Intel.StreamCodeWriter(ms);
assembler.Assemble(codeWriter, (ulong)0x40000);
Console.WriteLine(BitConverter.ToString(ms.ToArray()));
```
![image](https://github.com/icedland/iced/assets/14368203/e2fbc384-c20a-4542-bdb2-34783d1fddd8)

**Comment by wtfsck** [comment]
You need to change bitness to 64, it's currently 32.

**Comment by Symbai** [comment]
Isnt bpl the 8bit register of EBP? Why would that need 64bit? The other assembler I've used is also 32bit.

**Comment by wtfsck** [comment]
In 16 and 32-bit modes you can only access 8-bit regs: AL, CL, DL, BL, AH, CH, DH, BH.
