### ISSUE TITLE
vmmcall is treated as a call flow control

### ISSUE THREAD

**Issue by CR3Swapper** [icedland/iced#564]
Hi, just pointing this out maybe itll be changed, but when disassembling the instruction `vmmcall` the function `flow_control` returns `FlowControl::Call`. However it should probably just be treated as `FlowControl::Next`. 

Just pointing it out.

**Comment by wtfsck** [comment]
Yes, I've documented this as well.

If you only care about the CALL instructions, then you can check the mnemonic to see if it's 'Call'.
