### ISSUE TITLE
You must emit an instruction after emitting a label

### ISSUE THREAD

**Issue by aelio** [icedland/iced#571]
What is the use case for this check?
Can it be made optional at least?
I think assembler has no reason to take any care of this.
In my scenario I write assembly into standalone blocks and then bring them together without use of iced framework, so jump behind the last instruction is absolutely legal.

**Comment by wtfsck** [comment]
That's an implementation limitation. You can add the `Zero_bytes` "instruction" as the last instruction which won't write any bytes to the output.

**Comment by aelio** [comment]
Okay, thanks
