### ISSUE TITLE
Support for getting implicitly accessed registers

### ISSUE THREAD

**Issue by MIvanchev** [icedland/iced#600]
Hey, Capstone has a nice API to get what registers were implicitly read/written by an instruction. Is there something similar in iced?

**Comment by wtfsck** [comment]
https://github.com/icedland/iced/tree/master/src/java/iced-x86#get-instruction-info-eg-readwritten-regsmem-control-flow-info-etc

See the 'Used mem' and 'Used reg' lines in the output.

**Comment by MIvanchev** [comment]
Thank you very much!
