### ISSUE TITLE
rust iced-x86: Instruction::try_op_register is doc(hidden), but other docs try to link to it

### ISSUE THREAD

**Issue by lolbinarycat** [icedland/iced#602]
for example, [`Instruction::op0_register`](https://docs.rs/iced-x86/latest/iced_x86/struct.Instruction.html#method.op0_register) mentions it, but clicking on the link does nothing, since it isn't in the documentation.  many other methods have the same problem.

this seems like a handy method, why is it hidden?

**Comment by wtfsck** [comment]
There's some methods that were used before that couldn't be removed due to breaking code so they're hidden in the docs. I plan on removing these when 2.0 is released.

You should check if the operand is a register and the operand number is valid before calling op_register() so the try method is useless.

**Comment by lolbinarycat** [comment]
> You should check if the operand is a register and the operand number is valid before calling op_register() so the try method is useless.

"just always do the checks beforehand" is extremely unidiomatic in rust.

a huge part of the safety of rust comes from using algebraic data types (which rust calls enums) along with pattern matching to make it impossible to use a value without first checking if it is available.  this prevents accidentally reinterpreting bytes and getting a nonsense value, as is possible here.

if `try_op_register` is useless, then so is [slice::get](https://doc.rust-lang.org/std/primitive.slice.html#method.get).

**Comment by wtfsck** [comment]
There are no plans to update the API.

**Comment by lolbinarycat** [comment]
I am not asking for an update to the api.  I am asking for you to document the api, or at the very least remove `doc(hidden)` from it, or, if you absolutely insist on keeping it hidden, update the documentation to remove the links pointing to it.

If you want to deprecate the function, which it seems like you do, there is a dedicated attribute for deprication.  it is not `doc(hidden)`.

at the very least, the documentation should not contain links to a depricated/hidden function.

and if you see this as too low priority and don't want to do it yourself.. leave this open so someone else can fix it.

**Comment by wtfsck** [comment]
Feel free to send a PR to remove those refs from the docs.

I know about the deprecation attribute. Didn't want to add a bunch of warnings so it's been hidden and will be removed in a 2.x version.

**Comment by lolbinarycat** [comment]
y'know, i probably would've sent a PR.. but apparently this issue has already been "completed", and i've got better things to do.
