### ISSUE TITLE
Proposal : Alternative assembler usage for .NET

### ISSUE THREAD

**Issue by broudy3** [icedland/iced#95]
I would like to propose alternative way how to use Assembler. I would like to write code in a more natural way, where instance of "Assembler" class is not required and instruction functions are instead static. 
Like this, for example:

```
using static Iced.Intel.4Assembler;

public static ulong Test()
{
   mov(rax, 0x12345678);
   ret();

   // to satisfy compiler
   return 0;
}

static void Main(string[] args)
{
   Console.WriteLine(Test());
}
```

This would require some postbuild assembly weaving (Fody ?), similar to [InlineIL.Fody](https://github.com/ltrzesniewski/InlineIL.Fody) which is for IL code. 
For .NET Core/.NET Framework this could involve compiling such function at runtime, or maybe even creating mixed mode assembly.
For CoreRT code could be compiled AOT into an object file (#91), original function would be replaced with "extern" function with RuntimeImport attribute. Using this with CoreRT would be very interesting, because it would open doors for some interesting projects, like for example writing a OS kernel in pure C#.

**Comment by xoofx** [comment]
You can prototype this outside of Iced otherwise hooking into native codegen is currently not something super viable inside the .NET ecosystem. Without a deep support into the JIT runtime API, it will just stay a hack. There is little incentive to put this in Iced. I'm for example using Iced in a custom AOT compiler coupled with RyuJIT, but that's outside of .NET.

**Comment by broudy3** [comment]
Ok, my fault, I did not write it explicitly. I'm NOT proposing a inline assembler (like __asm keyword in Microsoft C++), this would be quite difficult to do and as you did write without JIT support it would be a hack.
In my proposal the code inside a function must only consist of calls to "Assembler" instructions (static functions). You also can not do antoher things, like using arguments (only via registers), or using fields.
So it more like syntactic sugar for .NET Core/.NET Framework, but for CoreRT it could be used to AOT compile assembler code.

**Comment by xoofx** [comment]
> Ok, my fault, I did not write it explicitly. I'm NOT proposing a inline assembler (like __asm keyword in Microsoft C++), this would be quite difficult to do and as you did write without JIT support it would be a hack.

That was not clear when you say the following:

> For .NET Core/.NET Framework this could involve compiling such function at runtime, or maybe even creating mixed mode assembly.

But otherwise, yes, you could write the code to an object file, compile a DLL with it, replace the code in Test by a DllImport at compile time with IL postprocessor..etc.... but that's a usage of Iced, you can pretty much do anything you want, but it doesn't mean that it should be part of Iced. But I will let @0xd4d comment on that.

**Comment by 0xd4d** [comment]
Yes I think this sounds like it's something that could be built on top of iced but not be part of it.

> In my proposal the code inside a function must only consist of calls to "Assembler" instructions (static functions).

If only instructions can be part of the method, then I guess you could just use an assembler.

You could just embed a string with the instructions, some msbuild task would pass it to eg. nasm, get the code, add it as native code to the .NET assembly and save it after removing the assembler string.

**Comment by hypeartist** [comment]
> In my proposal the code inside a function must only consist of calls to "Assembler" instructions (static functions). You also can not do antoher things, like using arguments (only via registers), or using fields.

You mean something like:
[https://github.com/hypeartist/AsmJit/blob/master/AsmJitTest/TestCases/RawAssembler.cs](https://github.com/hypeartist/AsmJit/blob/master/AsmJitTest/TestCases/RawAssembler.cs)
?
`Compile` method results in delegate 'pointing' to assembled bytecode which you can then invoke. Btw, with upcoming function pointers in C# 9 it would be even nicer, ig.

**Comment by wtfsck** [comment]
Closing since it's unlikely I'll ever implement this.
